//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVDLibraryADONET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVDTable
    {
        public string Title { get; set; }
        public string ReleaseDate { get; set; }
        public string Director { get; set; }
        public string Rating { get; set; }
        public int DVDID { get; set; }
        public string Notes { get; set; }
    }
}
